apply plugin: 'com.android.application'

android {
    compileSdk 37

    defaultConfig {
        applicationId "com.rafraph.pnineyHalachaHashalem"
        minSdkVersion 23
        multiDexEnabled true
        targetSdk 34
        versionCode 50400
        versionName "5.4.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.txt'
        }
    }

    buildFeatures {
        viewBinding true
        buildConfig true
    }
    namespace 'com.rafraph.pnineyHalachaHashalem'
    lint {
        abortOnError false
        checkReleaseBuilds false
    }
}

dependencies {
    implementation libs.androidx.legacy.support.v4
    implementation libs.androidx.appcompat
    implementation  files('libs/jsoup-1.7.3.jar')
    implementation libs.commons.net
    implementation libs.gson
    implementation libs.androidx.media
    implementation libs.androidx.recyclerview
    implementation libs.material
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.navigation.fragment
    implementation libs.androidx.navigation.ui
}